services:
  # Django
  app:
    build:
      context: app
      dockerfile: Dockerfile.development
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /usr/src/app/
    volumes:
      - ./app:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file:
      - .env.development
    depends_on:
      - db
      - redis
    networks:
      - front
      - back

  # celery
  celery:
    build:
      context: app
      dockerfile: Dockerfile.development
    command: celery -A app worker -l info
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env.development
    depends_on:
      - app
      - db
      - redis
    networks:
      - front
      - back

  # Postgres
  db:
    image: postgres:14.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env.development
    networks:
      - back

  # Redis
  redis:
    image: redis:latest
    networks:
      - back

volumes:
  db_data:
  static_volume:
  media_volume:

networks:
  front:
    external: false
  back:
    external: false
