# Generated by Django 3.2.7 on 2021-11-08 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Author ID')),
                ('Heading', models.CharField(help_text='著者名', max_length=100, verbose_name='Heading')),
            ],
        ),
        migrations.CreateModel(
            name='CutterSanbornThreeFigureAuthorTable',
            fields=[
                ('AuthorSymbol', models.CharField(blank=True, help_text='カッター・サンボーン著者記号', max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='Author Symbol')),
                ('AuthorName', models.CharField(help_text='著者名', max_length=50, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('LanguageCode', models.CharField(help_text='言語記号', max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Language Code')),
                ('Language', models.CharField(help_text='言語名', max_length=100, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectCode',
            fields=[
                ('SubjectCode', models.CharField(help_text='主題', max_length=6, primary_key=True, serialize=False, unique=True, verbose_name='Subject Code')),
                ('Language', models.CharField(help_text='言語名', max_length=100, verbose_name='Language')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorSymbol',
            fields=[
                ('AuthorSymbolId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Author Symbol ID')),
                ('AuthorSymbol', models.CharField(help_text='著者記号', max_length=50, verbose_name='Author Symbol')),
                ('AuthorId', models.ForeignKey(help_text='著者名', on_delete=django.db.models.deletion.CASCADE, related_name='Symbol', to='author_code.author', verbose_name='Author ID')),
                ('LanguageCode', models.ForeignKey(help_text='言語記号', on_delete=django.db.models.deletion.CASCADE, related_name='Authors', to='author_code.languagecode', verbose_name='Language Code')),
                ('SubjectCode', models.ForeignKey(help_text='請求記号２段目', on_delete=django.db.models.deletion.CASCADE, to='author_code.subjectcode', verbose_name='Subject Code')),
            ],
            options={
                'unique_together': {('AuthorId', 'LanguageCode', 'SubjectCode', 'AuthorSymbol')},
            },
        ),
        migrations.AddField(
            model_name='author',
            name='AuthorSymbol',
            field=models.ForeignKey(help_text='カッター・サンボーン著者記号', on_delete=django.db.models.deletion.CASCADE, related_name='Author', to='author_code.cuttersanbornthreefigureauthortable', verbose_name='Author Symbol'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('WorkId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Work ID')),
                ('WorkNumber', models.CharField(default='0', help_text='作品番号', max_length=20, verbose_name='Work Number')),
                ('WN', models.IntegerField(blank=True, help_text='ソート用WorkNumber', null=True, verbose_name='WN')),
                ('SeriesNumber', models.CharField(blank=True, help_text='シリーズ番号', max_length=20, null=True, verbose_name='Series Number')),
                ('SN', models.IntegerField(blank=True, help_text='ソート用SeriesNumber', null=True, verbose_name='SN')),
                ('BookTitle', models.CharField(help_text='書名', max_length=250, verbose_name='Book Title')),
                ('BookId', models.CharField(help_text='図書ID', max_length=10, verbose_name='Book ID')),
                ('AuthorSymbolId', models.ForeignKey(help_text='著者記号', on_delete=django.db.models.deletion.CASCADE, related_name='Work', to='author_code.authorsymbol', verbose_name='Author Symbol ID')),
            ],
            options={
                'unique_together': {('AuthorSymbolId', 'WorkNumber', 'SeriesNumber')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('AuthorSymbol', 'Heading')},
        ),
    ]
